import Head from "next/head";
import { Nunito } from "next/font/google";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
  ogTitle: "Admin Dashboard", // Open Graph title
  ogDescription: "Generated by create next app", // Open Graph description
  ogImage: "./images/admin.jpg", // Replace with the actual image URL
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Title */}
        <title>{metadata.title}</title>

        {/* Description */}
        <meta name="description" content={metadata.description} />

        {/* Open Graph tags */}
        <meta property="og:title" content={metadata.ogTitle} />
        <meta property="og:description" content={metadata.ogDescription} />
        <meta property="og:image" content={metadata.ogImage} />

        {/* Include Nunito font */}
        <link rel="stylesheet" href={nunito.href} />
      </Head>
      <body className={nunito.className}>{children}</body>
    </html>
  );
}
